#!/usr/bin/env php
<?php

require file_exists(__DIR__.'/vendor/autoload.php') ? __DIR__.'/vendor/autoload.php' : __DIR__.'/../../autoload.php';

$appVersion = '4.0-DEV';

$app = new Symfony\Component\Console\Application('Symfony WebServer', $appVersion);

$app->add(new Symfony\WebServer\Command\ServerLogCommand());
$app->add(new Symfony\WebServer\Command\ServerRunCommand());
$app->add(new Symfony\WebServer\Command\ServerStartCommand());
$app->add(new Symfony\WebServer\Command\ServerStatusCommand());
$app->add(new Symfony\WebServer\Command\ServerStopCommand());

$app->run();
